### PR TITLE
Added Breakfast Menu already

### PR DESCRIPTION
**Pull request by JiratchayaPhinyodom**
I added breakfast menu already.

### CODE REVIEW

**Comment by dzptahh** [comment]
50 is too much for sandwich

**Comment by pinpimarn** [comment]
I think you should describe more about the coffee. I don't understand that it's the cold coffee or hot coffee.

**Comment by crparichaya** [comment]
You should increase the price of coffee because nowadays, it is noticeable that coffee is more expensive than dessert or food.

**Comment by pinpimarn** [comment]
+1

**Comment by dzptahh** [comment]
+1

**Comment by crparichaya** [comment]
+1

**Pull request merged**
