### PR TITLE
Add 5 beverages on table

### PR DESCRIPTION
**Pull request by dzptahh**
The prices of the beverages are rather costly when compared to other stores in the canteen, and maybe 5 of the menu options are unsuitable for some people.

### CODE REVIEW

**Comment by pinpimarn** [comment]
I think "Thai Tea" is one of the famous baverage. You should add it to your menu.

**Comment by crparichaya** [comment]
Forget to Sort Letters on the menu list.

**Comment by JiratchayaPhinyodom** [comment]
Tea are hot or cold.

**Comment by JiratchayaPhinyodom** [comment]
+1

**Comment by pinpimarn** [comment]
+1

**Comment by crparichaya** [comment]
+1

**Comment by crparichaya** [comment]
+1

**Pull request merged**
