### PR TITLE
List dinner menu already

### PR DESCRIPTION
**Pull request by pinpimarn**
I'm not sure that is all the menu were listed good enough?

### CODE REVIEW

**Comment by dzptahh** [comment]
Is Tom Yum has any meat on it?

**Comment by crparichaya** [comment]
The price of food is too expensive.

**Comment by JiratchayaPhinyodom** [comment]
Check the black line and what meat in Thai green curry.

**Comment by dzptahh** [comment]
+1

**Comment by crparichaya** [comment]
+1

**Comment by JiratchayaPhinyodom** [comment]
+1

**Comment by crparichaya** [comment]
+1

**Comment by JiratchayaPhinyodom** [comment]
+1

**Comment by JiratchayaPhinyodom** [comment]
+1

**Comment by pinpimarn** [comment]
Team agree to merge.

**Pull request merged**
